export const publicationsData = [
  {
    title: "Physics-informed spatio-temporal network with trainable adaptive feature selection for short-term wind speed prediction",
    authors: ["Laeeq Aslam", "Runmin Zou", "Yaohui Huang", "Ebrahim Shahzad Awan", "Sharjeel Abid Butt", "Qian Zhou"],
    journal: "Computers and Electrical Engineering",
    year: 2025,
    volume: "126",
    pages: "110517",
    type: "journal",
    isFirstAuthor: true,
    pdfPath: "/papers/physics-informed-spatio-temporal-network.pdf",
    citations: 5,
  },
  {
    title: "Dynamic optimization of recurrent networks for wind prediction on edge devices",
    authors: ["Laeeq Aslam", "Runmin Zou", "Ebrahim Shahzad Awan", "Sayyed Shahid Hussain", "Muhammad Asim", "Samia Allaoua Chelloug"],
    journal: "IEEE Access",
    year: 2025,
    type: "journal",
    isFirstAuthor: true,
    pdfPath: "/papers/dynamic-optimization-recurrent-networks.pdf",
    citations: 3,
  },
  {
    title: "Hardware-centric exploration of the discrete design space in transformer-LSTM models for wind speed prediction on memory-constrained devices",
    authors: ["Laeeq Aslam", "Runmin Zou", "Ebrahim Shahzad Awan", "Sayyed Shahid Hussain", "Kashish Ara Shakil", "Mudasir Ahmad Wani", "Muhammad Asim"],
    journal: "Energies",
    year: 2025,
    volume: "18(9)",
    pages: "2153",
    type: "journal",
    isFirstAuthor: true,
    pdfPath: "/papers/hardware-centric-exploration-transformer-lstm.pdf",
    citations: 2,
  },
  {
    title: "Novel image steganography based on preprocessing of secrete messages to attain enhanced data security and improved payload capacity",
    authors: ["Laeeq Aslam", "Ahmad Saeed", "Ijaz Mansoor Qureshi", "Muhammad Amir", "Waseem Khan"],
    journal: "Traitement du Signal",
    year: 2020,
    volume: "37(1)",
    type: "journal",
    isFirstAuthor: true,
    pdfPath: "/papers/novel-image-steganography.pdf",
    citations: 8,
  },
  {
    title: "Effect of faulty sensors on estimation of direction of arrival and other parameters",
    authors: ["Laeeq Aslam", "Fawad Ahmad", "Sohail Akhtar", "Ebrahim Shahzad Awan", "Fatima Yaqoob"],
    journal: "Journal of Mechanics of Continua and Mathematical Sciences",
    year: 2020,
    volume: "15(4)",
    type: "journal",
    isFirstAuthor: true,
    pdfPath: "/papers/effect-faulty-sensors-doa.pdf",
    citations: 1,
  },
  // Journal Articles as Co-Author
  {
    title: "A new computing paradigm for off-grid direction of arrival estimation using compressive sensing",
    authors: ["Hamid Ali Mirza", "Laeeq Aslam", "Muhammad Asif Zahoor Raja", "Naveed Ishtiaq Chaudhary", "Ijaz Mansoor Qureshi", "Aqdas Naveed Malik"],
    journal: "Wireless Communications and Mobile Computing",
    year: 2020,
    volume: "2020(1)",
    pages: "9280198",
    type: "journal",
    isFirstAuthor: false,
    pdfPath: "/papers/new-computing-paradigm-doa.pdf",
    citations: 4,
  },
  {
    title: "Compressed sensing based image steganography system for secure transmission of audio message with enhanced security",
    authors: ["Muhammad Zaheer", "IM Qureshi", "Zeeshan Muzaffar", "Laeeq Aslam"],
    journal: "International Journal of Computer Science and Network Security",
    year: 2017,
    volume: "7",
    pages: "133–141",
    type: "journal",
    isFirstAuthor: false,
    pdfPath: "/papers/compressed-sensing-image-steganography.pdf",
    citations: 2,
  },
  // Conference Articles
  {
    title: "Integrating physics-informed vectors for improved wind speed forecasting with neural networks",
    authors: ["Laeeq Aslam", "Runmin Zou", "Ebrahim Awan", "Sharjeel Abid Butt"],
    journal: "2024 14th Asian Control Conference (ASCC)",
    year: 2024,
    pages: "1902–1907",
    type: "conference",
    isFirstAuthor: true,
    pdfPath: "/papers/integrating-physics-informed-vectors.pdf",
    citations: 1,
  },
  {
    title: "Exploring new frontiers in facial expression recognition: Dual densenet-201 and landmark distance analytics in the wild",
    authors: ["Abdullahi Mohamed Hassan", "Xiaojun Zhou", "Laeeq Aslam"],
    journal: "2024 IEEE 13th Data Driven Control and Learning Systems Conference (DDCLS)",
    year: 2024,
    pages: "2036–2043",
    type: "conference",
    isFirstAuthor: false,
    pdfPath: "/papers/exploring-facial-expression-recognition.pdf",
    citations: 0,
  },
  {
    title: "Towards efficient soh estimation for lithium-ion batteries via structural re-parameterization",
    authors: ["Qian Zhou", "Yun Wang", "Guang Wu", "Laeeq Aslam"],
    journal: "2024 IEEE 8th Conference on Energy Internet and Energy System Integration (EI2)",
    year: 2024,
    pages: "2658–2663",
    type: "conference",
    isFirstAuthor: false,
    pdfPath: "/papers/efficient-soh-estimation-batteries.pdf",
    citations: 1,
  },
];
